// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "mm_flowguard.h"
#include "softap_ota.h"
#include "flowguard_ui.h"
#include "esp_log.h"

///////////////////// VARIABLES ////////////////////
static const char *TAG = "UI.c";

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Label0;
void ui_event_Btn1(lv_event_t * e);
lv_obj_t * ui_Btn1;
lv_obj_t * ui_Btn1Lbl;
void ui_event_Btn2(lv_event_t * e);
lv_obj_t * ui_Btn2;
lv_obj_t * ui_Btn2Lbl;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES
lv_obj_t * uic_Screen1;

void ui_ScreenFWUpdate_screen_init(void);
lv_obj_t * ui_ScreenFWUpdate;
lv_obj_t * ui_LabelUpdate;
lv_obj_t * ui_LabelUpdate2;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        vTaskDelete(th_mm_flowguard);
        ESP_LOGI(TAG, "Meldung initialisieren");
        ui_ScreenFWUpdate_screen_init();
        ESP_LOGI(TAG, "Wifi starten");
        softap_ota_entry_func(0, NULL);
        ESP_LOGI(TAG, "Screen load");
        lv_disp_load_scr(ui_ScreenFWUpdate);
        ESP_LOGI(TAG, "UI-Update beenden");
        vTaskDelete(th_UI_Update);
        //vTaskDelete(th_LVGL);
    }
}
void cbScreenFWUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ESP_LOGI(TAG, "Update Screen loaded");
    }
}

void ui_event_Btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        fg.sensor=1;
    }
    else if(event_code==LV_EVENT_RELEASED)
    {
        fg.sensor=0;
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label2, target, "", " s");
        fg.offtime=lv_slider_get_value(target)*100; //save value as ms
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
