// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Btn1(lv_event_t * e);
extern lv_obj_t * ui_Btn1;
extern lv_obj_t * ui_Btn1Lbl;
void ui_event_Btn2(lv_event_t * e);
extern lv_obj_t * ui_Btn2;
extern lv_obj_t * ui_Btn2Lbl;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label0;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;

void ui_ScreenFWUpdate_screen_init(void);
extern lv_obj_t * ui_ScreenFWUpdate;
extern lv_obj_t * ui_LabelUpdate;
extern lv_obj_t * ui_LabelUpdate2;
void cbScreenFWUpdate(lv_event_t * e);
// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
