// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_image_recolor(ui_Screen1, lv_color_hex(0x76A7E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label0 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label0, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label0, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label0, 0);
    lv_obj_set_y(ui_Label0, 5);
    lv_obj_set_align(ui_Label0, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label0, "MOLCHMANUFAKTUR");

    ui_Btn1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Btn1, 50);
    lv_obj_set_height(ui_Btn1, 20);
    lv_obj_set_x(ui_Btn1, 5);
    lv_obj_set_y(ui_Btn1, 5);
    lv_obj_add_flag(ui_Btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Btn1, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_Btn1, lv_color_hex(0x76A7E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn1Lbl = lv_label_create(ui_Btn1);
    lv_obj_set_width(ui_Btn1Lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Btn1Lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Btn1Lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Btn1Lbl, LV_SYMBOL_SETTINGS);

    ui_Btn2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Btn2, 50);
    lv_obj_set_height(ui_Btn2, 20);
    lv_obj_set_x(ui_Btn2, -5);
    lv_obj_set_y(ui_Btn2, 5);
    lv_obj_set_align(ui_Btn2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Btn2, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_Btn2, lv_color_hex(0x76A7E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Btn2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btn2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn2Lbl = lv_label_create(ui_Btn2);
    lv_obj_set_width(ui_Btn2Lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Btn2Lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Btn2Lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Btn2Lbl, LV_SYMBOL_REFRESH);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 50);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "13");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label5, 10);
    lv_obj_set_y(ui_Label5, 50);
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "Angehalten:");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -75);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "5.7 s");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label3, -10);
    lv_obj_set_y(ui_Label3, -30);
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label3, "An");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label4, 10);
    lv_obj_set_y(ui_Label4, -30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label4, "Aus");

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 250);
    lv_obj_set_height(ui_Slider1, 30);
    lv_obj_set_x(ui_Slider1, 0);
    lv_obj_set_y(ui_Slider1, -10);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x76A7E4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x76A7E4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if (lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0)
        lv_obj_set_style_pad_right(ui_Slider1,
                                   lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 250);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 100);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_image_recolor(ui_Bar1, lv_color_hex(0x76A7E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x76A7E4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Bar1, lv_color_hex(0x76A7E4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if (lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0)
        lv_obj_set_style_pad_right(ui_Bar1,
                                   lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Btn1, ui_event_Btn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn2, ui_event_Btn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    uic_Screen1 = ui_Screen1;
}
